CREATE SMALLFILE TABLESPACE NIJU 
    DATAFILE 
        '/opt/oracle/movies/SPECIFICATION' SIZE 2147483648 
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

-- USER SQL
CREATE USER "NIJU" IDENTIFIED BY "NIJU321"  
DEFAULT TABLESPACE "NIJU";

ALTER USER NIJU quota unlimited on NIJU;

-- ROLES
GRANT "CONNECT" TO "NIJU" ;
GRANT "RESOURCE" TO "NIJU" ;

SET DEFINE OFF
CREATE TABLE GENOME_SCORES ( movie_id NUMBER(38),
tag_id NUMBER(38),
relevance FLOAT);

CREATE TABLE GENOME_TAGS ( tag_id NUMBER(38),
tag VARCHAR2(256));

CREATE TABLE LINKS ( movie_id NUMBER(38),
imdb_id NUMBER(38),
tmdb_id NUMBER(38));

CREATE TABLE MOVIES ( movie_id NUMBER(38),
title VARCHAR2(256),
genres VARCHAR2(256));

CREATE TABLE RATINGS ( user_id NUMBER(38),
movie_id NUMBER(38),
rating FLOAT,
timestamp NUMBER(38));

CREATE TABLE TAGS ( user_id NUMBER(38),
movie_id NUMBER(38),
tag VARCHAR2(128),
timestamp NUMBER(38));


ALTER TABLE MOVIES
ADD CONSTRAINT PK_MOVIES PRIMARY KEY (MOVIE_ID);

ALTER TABLE LINKS
ADD CONSTRAINT FK_LINKS FOREIGN KEY (MOVIE_ID)
REFERENCES  MOVIES (MOVIE_ID);

ALTER TABLE RATINGS
ADD CONSTRAINT FK_RATINGS_MOVIES FOREIGN KEY (MOVIE_ID)
REFERENCES  MOVIES (MOVIE_ID);

ALTER TABLE TAGS
ADD CONSTRAINT FK_TAGS_MOVIES FOREIGN KEY (MOVIE_ID)
REFERENCES  MOVIES (MOVIE_ID);

ALTER TABLE GENOME_TAGS
ADD CONSTRAINT PK_GENOME_TAGS PRIMARY KEY (TAG_ID);

ALTER TABLE GENOME_SCORES
ADD CONSTRAINT FK_GENOME_SCORES_MOVIES FOREIGN KEY (MOVIE_ID)
REFERENCES  MOVIES (MOVIE_ID);

ALTER TABLE GENOME_SCORES
ADD CONSTRAINT FK_GENOME_SCORES_GENOME_TAGS FOREIGN KEY (TAG_ID)
REFERENCES  GENOME_TAGS (TAG_ID);

-- Modify dates column

ALTER TABLE RATINGS ADD (DATETIME TIMESTAMP);

UPDATE RATINGS SET DATETIME = TO_TIMESTAMP(
                TO_CHAR( 
                TO_DATE( '1970-01-01', 'YYYY-MM-DD' ) + numtodsinterval( TIMESTAMP, 'SECOND' ), 
                'YYYY-MM-DD HH24:MI:SS'
                ), 'YYYY-MM-DD HH24:MI:SS');
                
ALTER TABLE RATINGS DROP COLUMN TIMESTAMP;

ALTER TABLE TAGS ADD (DATETIME TIMESTAMP);

UPDATE TAGS SET DATETIME = TO_TIMESTAMP(
                TO_CHAR( 
                TO_DATE( '1970-01-01', 'YYYY-MM-DD' ) + numtodsinterval( TIMESTAMP, 'SECOND' ), 
                'YYYY-MM-DD HH24:MI:SS'
                ), 'YYYY-MM-DD HH24:MI:SS');
            
ALTER TABLE TAGS DROP COLUMN TIMESTAMP;

-- Temporal table

CREATE TABLE TEMPORAL (
id_1 VARCHAR2(256),
id_2 VARCHAR2(256),
value_1 VARCHAR2(256),
value_2 VARCHAR2(256)
);

ALTER TABLE TEMPORAL MODIFY (value_1 VARCHAR2(2000), VALUE_2 VARCHAR2(2000));