-- RELATIONS

ALTER TABLE MOVIES
ADD CONSTRAINT PK_MOVIES PRIMARY KEY (MOVIE_ID);

ALTER TABLE LINKS
ADD CONSTRAINT FK_LINKS FOREIGN KEY (MOVIE_ID)
REFERENCES  MOVIES (MOVIE_ID);

ALTER TABLE RATINGS
ADD CONSTRAINT FK_RATINGS_MOVIES FOREIGN KEY (MOVIE_ID)
REFERENCES  MOVIES (MOVIE_ID);

ALTER TABLE TAGS
ADD CONSTRAINT FK_TAGS_MOVIES FOREIGN KEY (MOVIE_ID)
REFERENCES  MOVIES (MOVIE_ID);

ALTER TABLE GENOME_TAGS
ADD CONSTRAINT PK_GENOME_TAGS PRIMARY KEY (TAG_ID);

ALTER TABLE GENOME_SCORES
ADD CONSTRAINT FK_GENOME_SCORES_MOVIES FOREIGN KEY (MOVIE_ID)
REFERENCES  MOVIES (MOVIE_ID);

ALTER TABLE GENOME_SCORES
ADD CONSTRAINT FK_GENOME_SCORES_GENOME_TAGS FOREIGN KEY (TAG_ID)
REFERENCES  GENOME_TAGS (TAG_ID);
