CREATE SMALLFILE TABLESPACE NIJU 
    DATAFILE 
        '/opt/oracle/movies/SPECIFICATION' SIZE 2147483648 
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;
